version: "3.7"

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./views:/var/www 
  
  mysql:
    build:
      context: ./mysql
    ports:
      - "3307:3306"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/dbTemp:/temp/mysql
      - ./mysql/dbLog:/var/log/mysql
      - ./mysql/dbMigrations:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - php-fpm
    links:
      - mysql

  nginx:
    build:
      context: ./nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./views:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm

  nodejs:
    build:
      context: ./nodejs
    volumes:
      - ./nodejs:/nodejs/app/
      - ./nodejs/app/node_modules/
    ports:
      - 3000:3000
    container_name: nodejs
    restart: always
    depends_on:
      - mysql

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: //c/Users/dolnm/Documents/archiv/views/
      o: bind